### ISSUE TITLE
Broadcast error when changing from L2-norm to L1-norm

### ISSUE THREAD

**Issue by filippobistaffa** [epfl-lts2/pyunlocbox#33]
I consider the following very simple least-squares problem with `x` as trivial solution:
```python
from pyunlocbox import functions, solvers, acceleration
import numpy as np

n = 3
a = 2
A = np.eye(n)
A = np.concatenate([A] * a, 0)
x = np.random.rand(A.shape[1])
print(x)
y = A @ x
f = functions.norm_l2(y=y, A=A)
dummy = functions.dummy()
step = 1 / np.linalg.norm(A.T @ A)
solver = solvers.gradient_descent(step=step)
x0 = np.ones_like(x)
ret = solvers.solve([f, dummy], x0, solver, atol=1e-5, verbosity='HIGH')
print(ret['sol'])
```
which correctly returns `x`. On the other hand, if I switch to L1 (`f = functions.norm_l1(y=y, A=A)`) I get a broadcast error:
```python
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    ret = solvers.solve([f, dummy], x0, solver, atol=1e-5, verbosity='HIGH')
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/solvers.py", line 250, in solve
    solver.pre(functions, x0)
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/solvers.py", line 378, in pre
    self._pre(functions, self.sol)
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/solvers.py", line 475, in _pre
    if 'GRAD' in f.cap(x0):
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/functions.py", line 343, in cap
    self.prox(x, 1)
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/functions.py", line 281, in prox
    return self._prox(np.asarray(x), T)
  File "/usr/local/lib/python3.8/dist-packages/pyunlocbox/functions.py", line 450, in _prox
    sol[:] = x + self.At(sol) / self.nu
ValueError: could not broadcast input array from shape (3) into shape (6)
```
Why is that?

**Comment by mdeff** [comment]
The code assumes a square matrix `A`. I don't know whether we can easily generalize it (do you?) or if we should raise an exception when the matrix isn't square.

**Comment by mdeff** [comment]
Thanks for reporting. There was an issue in the code which made it assume a square matrix `A`.
